name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - develop
      - release
      - feature/*
      - hotfix/*
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - release
      - develop
      - feature/*
      - hotfix/*

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI

      - name: Installeer MAUI workloads
        run: dotnet workload install maui

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Bouw de applicatie
        run: dotnet build --configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp-build
          path: |
            **/bin/Release/
            !**/*.pdb   # (optioneel: exclude symbol files)

      - name: Voer unit tests uit en genereer resultaten
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Upload testresultaten
        if: always()   # ook uploaden als tests falen
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults
